### ISSUE TITLE
[FEATURE] Standalone Android download / f-droid app

### ISSUE THREAD

**Issue by Kollides** [Jinjinov/Ididit#3]
I love the app! 

However it seems to be only downloadable through Google Play Store. 

Would it be possible to have it downloadable straight from the github page or from F-droid?

**Comment by Jinjinov** [comment]
I am glad that you like the app! :)

I am searching for "F-Droid" now... interesting... but it looks like even more work

It took me 2 month to publish it on Windows, Android and iOS and I still haven't published it on macOS store and Debian / Ubuntu repository... I have 10 unsuccessful attempts to publish it on macOS store... I don't have any experience with publishing apps, so this is very frustrating - I wish that publishing would be easier...

I can't promise that I will publish it on F-Droid soon... any help with publishing would be appreciated :)

**Comment by Jinjinov** [comment]
I finally took the time to look if I can publish to F-Droid, but it seems like they want everything to be built from source... not just your app, but EVERYTHING, which includes building the entire Microsoft .NET from source - which is almost impossible, because even Microsoft uses binary tools when they build .NET from source... you would have to build tools to build the tools to build .NET to build your app...

You can read more at:
https://forum.f-droid.org/t/why-isnt-c-net-maui-supported/24842

**Comment by Jinjinov** [comment]
Standalone Android download is available at:

https://apkpure.com/ididit/com.jinjinov.ididit
